Feature/myfriends
find-frend/find_friend_backend pull request #103
Opened 2024-03-04 16:28 UTC by N0len-sasha

Добавлен вывод user, которые являются друзьями текущего пользователя по GET запросу на http://127.0.0.1:8000/api/v1/users/myfriends/

2024-03-04 23:41 UTC, Dnevvs commented on src/api/views.py
> +    def my_friends(self, request):
На отсутствие докстринга коммит не ругается?

2024-03-05 10:22 UTC, Esperansa08 commented on src/api/views.py
> +    def my_friends(self, request):
добавь докстринг

2024-03-05 10:23 UTC, Esperansa08 requested changes
добавь докстринг

2024-03-06 05:42 UTC, Esperansa08 approved these changes

2024-03-06 07:06 UTC, merged